language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 3.0
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
  # - ./scripts/dotnet-test-unit.sh
  # - ./scripts/dotnet-test-e2e.sh
  - ./scripts/dotnet-publish.sh
  - ./scripts/docker-publish.sh
after_success:
  - ./scripts/after-success.sh
notifications:
  email:
    on_success: never
    on_failure: never