language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 3.0
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
jobs:
  include:
    - stage: build
      script:
        - ./scripts/dotnet-build.sh
    - stage: test
      script:
        - ./scripts/dotnet-test-unit.sh
        - ./scripts/dotnet-test-e2e.sh
    - stage: publish
      script:
        - ./scripts/dotnet-publish.sh
        - ./scripts/docker-publish.sh
stages:
  - build
  - test
  - publish
notifications:
  email:
    on_success: never
    on_failure: never
      