version: "2"

services:
  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
    command: mongo:27017

  api:
    build: ../src/StockAdvisor.Api
    links:
      - mongo
    ports:
      - '5000:5000'

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'