version: "2"

services:
  api:
    build: ../src/StockAdvisor.Api
    links:
      - mongo
      - mssql
    ports:
      - '5000:5000'

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'

  mssql:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "12345"
    ports:
      - "1433:1433"